import Student from "../Student/Student";
import "./Students.css";

const studentList = [
  {
    firstName: "שרה",
    lastName: "לוי",
    id: 305493284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "חיה",
    lastName: "כהן",
    id: 305233284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "נועה",
    lastName: "דגן",
    id: 305494284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "שרה",
    lastName: "לוי",
    id: 305493286,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "חיה",
    lastName: "כהן",
    id: 305633284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "נועה",
    lastName: "דגן",
    id: 305496284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "שרה",
    lastName: "לוי",
    id: 315493284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "חיה",
    lastName: "כהן",
    id: 305234284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "נועה",
    lastName: "דגן",
    id: 305394284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "שרה",
    lastName: "לוי",
    id: 305293284,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "חיה",
    lastName: "כהן",
    id: 305233214,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
  {
    firstName: "נועה",
    lastName: "דגן",
    id: 305494184,
    dateOfBirth: new Date("03/25/2000"),
    phoneNumber: 5026637201,
    emailAddress: "fake@gmail.com",
    Theory: false,
    numberOfLessons: 3,
    testDate: new Date(),
    pricePerLesson: 140,
    internalTest: false,
    registrationFees: true,
    enteredSchool: true,
    //   debt: false,
    payment: 280,
  },
];
const Students = () => {
  return (
    <div className="students">
      <h2 className="title-students">רשימת תלמידים</h2>
      <div className="collapse-container">
        {studentList.map((student) => (
          <Student key={student.id} student={student} />
        ))}
      </div>
      <footer id="footerStudents">{`סה"כ: ${studentList.length} תלמידים`}</footer>
    </div>
  );
};

export default Students;
